version: '3'

services:
    couchdb:
        image: couchdb:latest
        container_name: couchdb.react-couchdb-todo.docker
        restart: always
        volumes:
            - ~/data/couchdb.react-todo.docker:/usr/local/var/lib/couchdb
        env_file:
            - ./.env
        ports:
            - 127.0.0.1:${COUCHDB_PORT}:5984
        networks:
            - global

    redis:
        image: redis:latest
        container_name: redis.react-couchdb-todo.docker
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command:
            - 'bash'
            - '-c'
            - 'docker-entrypoint.sh --requirepass "$$REDIS_PASSWORD"'
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379
        networks:
            - global

networks:
    global:
        external: true
