version: '3'

volumes:
    couchdb.data:
    redis.data:

services:
    couchdb:
        image: couchdb:latest
        container_name: ${COMPOSE_PROJECT_NAME}.couchdb.docker
        restart: unless-stopped
        volumes:
            - couchdb.data:/usr/local/var/lib/couchdb
        ports:
            - 127.0.0.1:${COUCHDB_PORT}:5984
        networks:
            - global

    redis:
        image: redis:latest
        container_name: ${COMPOSE_PROJECT_NAME}.redis.docker
        restart: unless-stopped
        volumes:
            - redis.data:/data
        command: redis-server --requirepass ${REDIS_SESSION_PASS}
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379
        networks:
            - global

networks:
    global:
        external: true
